### PR TITLE
Added new methods + lint files

### PR DESCRIPTION
**Pull request by QuentiumYT**
Hey, I saw this project and wanted to contribute with my own needs

I've added the findall and delete methods in the wrapper, it works great on my own. (testing with https://github.com/drodimin/drive-appdata-cient-app)

Note: I did not added any jest tests.

Hope you will find it useful :)

### CODE REVIEW

**Comment by drodimin** [comment]
Hi, This looks good and makes sense to add these methods. Is there a chance you can add unit tests in client.test.js for the new methods. You can just follow the pattern for the other methods. It is not a big deal if you can't. Just let me know and then I will merge your changes and update the package in the npm registry. Thank you.

**Comment by QuentiumYT** [comment]
Hi, here are some tests. I'm not good at writing JS tests and I'm unsure about the ones I've written.
Delete method resolve an undefined status and findAll throws an error, if you got a clue, I'd change the resolve error case

**Comment by drodimin** [comment]
No worries, I have adjusted the tests. The new package is now published. I renamed the **findAll** method to **list** to better reflect what it is doing. Thanks for contributing.

**Comment by QuentiumYT** [comment]
Alright, thanks for the adjustments, happy to see it live :)

**Pull request merged**
